### ISSUE TITLE
packages.aosc.io website: `error returned from database: (code: 14) unable to open database file`

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/packages-site-rs#5]
Error above is returned when browsing https://packages.aosc.io

**Comment by eatradish** [comment]
Known issue...and @liushuyu

**Comment by luzpaz** [comment]
Link to any open issue this is a dupe of ?

**Comment by MingcongBai** [comment]
> Link to any open issue this is a dupe of ?

The current implementation fixes this issue via a major database overhaul, try it out!
